esphome:
 name: media-controller
 friendly_name: media-controller
 comment: ESPHome media-controller
 name_add_mac_suffix: true
 platform: ESP8266
 board: nodemcuv2

 # This will allow for (future) project identification, configuration and updates.
 project:
   name: esphome.media-controller
   version: "1.0"

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:
 encryption:
   key: bnfP0RlrDw5eEUMcIXhA2loLCLYWWEpwKoAWjL6YBJM=

# OTA is required for Over-the-Air updating
ota:

# Network settings
wifi:
 ssid: !secret wifiSSID
 password: !secret wifiPASS
 manual_ip:
  static_ip: 192.168.1.31
  gateway: 192.168.1.1
  subnet: 255.255.255.0

 # Enable fallback hotspot (captive portal) in case wifi connection fails
 ap:
   ssid: !secret wifiSSID
   password: !secret wifiPASS

captive_portal:

web_server:
 port: 80

binary_sensor:
# Key switches
- platform: gpio
  pin:
    number: D5
    mode: INPUT_PULLUP
    inverted: True
  name: "Left Button"
  filters:
    - delayed_on: 10ms
- platform: gpio
  pin:
    number: D6
    mode: INPUT_PULLUP
    inverted: True
  name: "Middle Button"
  filters:
    - delayed_on: 10ms
- platform: gpio
  pin:
    number: D7
    mode: INPUT_PULLUP
    inverted: True
  name: "Right Button"
  filters:
    - delayed_on: 10ms


# Rotary Encoder
- platform: gpio
  pin:
    number: D2
    mode: INPUT_PULLUP
    inverted: true
  name: "Rotary Encoder Button"

sensor:
  - platform: rotary_encoder
    name: "Rotary Encoder"
    pin_a:
      number: D3
      mode: INPUT
    pin_b:
      number: D4
      mode: INPUT
    resolution: 2
    
# Network details
text_sensor:
- platform: wifi_info
  ip_address:
    name: ${device_name} IP
    icon: mdi:ip-network
  ssid:
    name: ${device_name} SSID
    icon: mdi:wifi
  mac_address:
    name: "${device_name} MAC"
    icon: mdi:identifier
